[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "lm_deluge"
version = "0.0.3"
authors = [{ name = "Benjamin Anderson", email = "ben@trytaylor.ai" }]
description = "Python utility for using LLM API models."
readme = "README.md"
requires-python = ">=3.10"
keywords = []
license = { text = "" }
classifiers = []
dependencies = [
    "python-dotenv",
    "json5",
    "PyYAML",
    "pandas",
    "aiohttp",
    "tiktoken",
    "xxhash",
    "tqdm",
    "google-auth",
    "requests-aws4auth",
    "pydantic",
    "bs4",
    "lxml",
]

[project.optional-dependencies]
image = ["pdf2image", "pillow"]
pdf = ["pdf2image", "pymupdf"]
translate = ["fasttext-wheel", "fasttext-langdetect"]
full = [
    "pillow",
    "pdf2image",
    "pymupdf",
    "fasttext-wheel",
    "fasttext-langdetect",
]
